# Generated by Django 5.1 on 2024-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("seat", "guest_name", "booking_date", "booking_time"),
                name="unique_booking",
            ),
        ),
    ]
