# Generated by Django 5.1 on 2024-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_unique_together_booking_unique_booking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("seat", "guest_name", "booking_date"), name="unique_booking"
            ),
        ),
    ]
