# Generated by Django 5.1 on 2024-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_booking_unique_booking_booking_unique_booking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("seat", "booking_date", "booking_time"),
                name="unique_booking_per_time_slot",
            ),
        ),
    ]
