# Generated by Django 5.1 on 2024-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_venue_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("venue", "seat_number"), name="unique_seat_per_venue"
            ),
        ),
    ]
